### ISSUE TITLE
broken promisepipe@2.1.1 

### ISSUE THREAD

**Issue by yinrong** [epeli/node-promisepipe#13]
my usage
```js
  await $.promisePipe(prj.epic, csvToJson(), $.es.through(async l => { ......
```
error:
```
TypeError: s.removeAllListeners is not a function
    at events.map.e (node_modules/promisepipe/index.js:16:42)
    at Array.map (<anonymous>)
    at streams.forEach.s (node_modules/promisepipe/index.js:16:31)
    at Array.forEach (<anonymous>)
    at cleanupEventHandlers (node_modules/promisepipe/index.js:16:11)
    at Promise.all.then (node_modules/promisepipe/index.js:58:5)
    at <anonymous>
```

workaround:
```
  "dependencies": {

    "promisepipe": "2.0.0",

```

**Comment by MartinKolarik** [comment]
Should be fixed in v2.1.2
